
-- Affliction priority lists, in-game cure orders, and cure lists

-- :: Globals

-- :::: Moss afflictions

g_pMossAffs_head = add_item(g_pMossAffs_head, "plodding")
g_pMossAffs_head = add_item(g_pMossAffs_head, "idiocy")

-- :::: Tree afflictions


g_pTreeAffs_head = add_item(g_pTreeAffs_head, "left_leg_broken")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "right_leg_broken")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "left_arm_broken")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "right_arm_broken")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "sandrot")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "dizziness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "masochism")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "mirroring")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "mental_disruption")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "physical_disruption")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "itching")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "dementia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "generosity")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "madness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "blurry_vision")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "shyness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "crippled_throat")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "vomiting")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "stupidity")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "addiction")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "plodding")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "confusion")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "justice")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "stuttering")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "idiocy")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "hallucinations")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "deadening")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "vertigo")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "haemophilia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "aeon")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "sunlight_allergy")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "epilepsy")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "shivering")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "agoraphobia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "claustrophobia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "weariness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "clumsiness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "magic_impaired")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "ablaze")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "frozen")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "hatred")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "loneliness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "lethargy")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "hellsight")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "dissonance")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "hypochondria")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "sensitivity")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "paranoia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "body_odor")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "disfigurement")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "slickness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "hypersomnia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "thin_blood")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "recklessness")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "broken_limb")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "withering")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "rend")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "anorexia")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "asthma")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "impatience")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "destroyed_throat")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "unknown_focus")
g_pTreeAffs_head = add_item(g_pTreeAffs_head, "unknown")

-- :::: Renew afflictions

g_pRenewAffs_head = add_item(g_pRenewAffs_head, "left_leg_broken")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "right_leg_broken")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "left_arm_broken")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "right_arm_broken")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "dizziness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "masochism")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "mirroring")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "mental_disruption")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "physical_disruption")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "itching")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "dementia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "generosity")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "madness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "blurry_vision")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "shyness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "crippled_throat")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "vomiting")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "stupidity")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "addiction")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "plodding")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "confusion")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "anorexia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "justice")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "stuttering")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "idiocy")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "hallucinations")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "deadening")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "vertigo")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "haemophilia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "aeon")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "sunlight_allergy")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "epilepsy")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "shivering")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "agoraphobia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "claustrophobia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "weariness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "clumsiness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "magic_impaired")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "ablaze")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "frozen")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "hatred")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "loneliness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "lethargy")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "hellsight")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "dissonance")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "hypochondria")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "sensitivity")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "paranoia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "body_odor")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "disfigurement")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "slickness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "hypersomnia")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "thin_blood")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "recklessness")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "broken_limb")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "destroyed_throat")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "withering")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "asthma")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "impatience")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "sandrot")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "paralysis")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "rend")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "unknown_focus")
g_pRenewAffs_head = add_item(g_pRenewAffs_head, "unknown")
	
-- :::: Focus afflictions
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "stupidity")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "anorexia")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "epilepsy")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "mirroring")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "paranoid")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "hallucinations")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "shyness")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "stuttering")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "dizziness")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "indifference")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "berserking")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "pacifism")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "lovers_effect")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "hatred")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "generosity")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "claustrophobia")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "vertigo")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "loneliness")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "agroaphobia")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "masochism")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "recklessness")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "weariness")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "confusion")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "dementia")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "premonition")
g_pFocusAffs_head = add_item(g_pFocusAffs_head, "unknown_focus")

-- :::: Writhe afflictions

g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_web");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_transfix");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_armpitlock");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_thighlock");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_necklock");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_bind");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_vines");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_ropes");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_feed");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "writhe_impaled");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "grappled");
g_pWritheAffs_head = add_item(g_pWritheAffs_head, "mob_impaled");

-- :::: Writhe cures

g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_impaled", "impale");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_transfix", "transfix");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_armpitlock", "armpit-jawlock");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_web", "web");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_thighlock", "thigh-jawlock");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_vines", "vines");
g_pWritheCures_head = add_key(g_pWritheCures_head, "feed", "feed");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_necklock", "neck-jawlock");
g_pWritheCures_head = add_key(g_pWritheCures_head, "claws", "claws");
g_pWritheCures_head = add_key(g_pWritheCures_head, "roped", "noose");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_ropes", "ropes");
g_pWritheCures_head = add_key(g_pWritheCures_head, "writhe_bind", "bind");
g_pWritheCures_head = add_key(g_pWritheCures_head, "grappled", "grapple");
g_pWritheCures_head = add_key(g_pWritheCures_head, "mob_impaled", "mob_impaled");

-- :::: Pipe afflictions
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "aeon");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "slickness");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "disfigurement");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "hellsight");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "madness");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "deadening");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "withering");
g_pPipeAffs_head = add_item(g_pPipeAffs_head, "noaura");

-- :::: Pipe cures
g_pPipeCures_head = add_key(g_pPipeCures_head, "hellsight", "elm");
g_pPipeCures_head = add_key(g_pPipeCures_head, "withering", "elm");
g_pPipeCures_head = add_key(g_pPipeCures_head, "slickness", "valerian");
g_pPipeCures_head = add_key(g_pPipeCures_head, "deadening", "elm");
g_pPipeCures_head = add_key(g_pPipeCures_head, "disfigurement", "valerian");
g_pPipeCures_head = add_key(g_pPipeCures_head, "madness", "valerian");
g_pPipeCures_head = add_key(g_pPipeCures_head, "noaura", "skullcap");
g_pPipeCures_head = add_key(g_pPipeCures_head, "aeon", "elm");

-- :::: Salve afflictions
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "indifference")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "anorexia")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "destroyed_throat")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "crushed_chest")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "cracked_ribs")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "head_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_dislocated")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_dislocated")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "leg_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_leg_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_leg_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "crushed_kneecaps")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "crushed_elbows")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "crippled_throat")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "damaged_throat")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "head_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "head_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "head_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "head_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "torso_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "torso_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "spinal_rip")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "torso_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "torso_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "torso_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_bruised_critical")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_mangled")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_damaged")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_dislocated")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_dislocated")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "arm_broken")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_bruised_moderate")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "left_arm_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "right_arm_bruised")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "broken_limb")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "frozen")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "gorge")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "blurry_vision")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "nodensity")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "shivering")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "nocaloric")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "ablaze")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "stuttering")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "throat_slash")
g_pSalveAffs_head = add_item(g_pSalveAffs_head, "burnt_eyes")

-- :::: Salve cures
g_pSalveCures_head = add_key(g_pSalveCures_head, "crushed_kneecaps", "mending to legs")
g_pSalveCures_head = add_key(g_pSalveCures_head, "crushed_elbows", "mending to arms")
g_pSalveCures_head = add_key(g_pSalveCures_head, "cracked_ribs", "mending to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "crushed_chest", "restoration to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "nocaloric", "caloric to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "head_mangled", "restoration to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "stuttering", "epidermal to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "lost_spiritbond", "mending to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_damaged", "restoration to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_damaged", "restoration to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "crippled_throat", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "indifference", "epidermal to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "ablaze", "mending to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "damaged_throat", "restoration to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "head_damaged", "restoration to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "spinal_rip", "restoration to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "shivering", "caloric to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "destroyed_throat", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_dislocated", "mending to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_dislocated", "mending to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_dislocated", "mending to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_dislocated", "mending to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_bruised_critical", "mending to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_bruised_critical", "mending to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_bruised_critical", "mending to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_bruised_critical", "mending to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_bruised_moderate", "mending to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_bruised_moderate", "mending to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_bruised_moderate", "mending to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_bruised_moderate", "mending to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_bruised", "mending to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_bruised", "mending to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_bruised", "mending to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_bruised", "mending to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_broken", "mending to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_broken", "mending to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "arm_broken", "mending to arms")
g_pSalveCures_head = add_key(g_pSalveCures_head, "leg_broken", "mending to legs")
g_pSalveCures_head = add_key(g_pSalveCures_head, "gorge", "epidermal to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_mangled", "restoration to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_mangled", "restoration to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "blurry_vision", "epidermal to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "nodensity", "mass to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "frozen", "caloric to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_leg_mangled", "restoration to left leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "left_arm_mangled", "restoration to left arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_damaged", "restoration to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_damaged", "restoration to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "broken_limb", "mending to skin")
g_pSalveCures_head = add_key(g_pSalveCures_head, "torso_mangled", "restoration to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "throat_slash", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "anorexia", "epidermal to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "torso_damaged", "restoration to torso")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_leg_broken", "mending to right leg")
g_pSalveCures_head = add_key(g_pSalveCures_head, "right_arm_broken", "mending to right arm")
g_pSalveCures_head = add_key(g_pSalveCures_head, "burnt_eyes", "epidermal to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "head_bruised_critical", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "head_bruised_moderate", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "head_bruised", "mending to head")
g_pSalveCures_head = add_key(g_pSalveCures_head, "torso_bruised_critical", "mending to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "torso_bruised_moderate", "mending to body")
g_pSalveCures_head = add_key(g_pSalveCures_head, "torso_bruised", "mending to body")

-- :::: Herb afflictions

g_pHerbAffs_head = add_item(g_pHerbAffs_head, "paralysis")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "asthma")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "thin_blood")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "limp_veins")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "sandrot")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "physical_disruption")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "mental_disruption")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "clumsiness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "magic_impaired")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "impatience")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "confusion")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "stupidity")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "mirroring")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "haemophilia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "sensitivity")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "crippled")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "crippled_body")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "rend")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "weariness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "masochism")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "sunlight_allergy")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "vomiting")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "hypochondria")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "hypersomnia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "unblind")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "slickness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "heartflutter")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "lethargy")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "blood_poison")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "blood_curse")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "epilepsy")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "hallucinations")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "berserking")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "recklessness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "undeaf")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "pacifism")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "peace")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "lovers_effect")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "hatred")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "justice")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "dizziness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "dissonance")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "shyness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "vertigo")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "agoraphobia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "claustrophobia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "dementia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "loneliness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "generosity")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "paranoia")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "baldness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "self-pity")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "body_odor")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "commitment_fear")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "sadness")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "hubris")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "addiction")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "nopear")
g_pHerbAffs_head = add_item(g_pHerbAffs_head, "resonance")

-- :::: Herb cures
g_pHerbCures_head = add_key(g_pHerbCures_head, "mirroring", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "crippled", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "crippled_body", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "mental_disruption", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "physical_disruption", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "rend", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "claustrophobia", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "body_odor", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "heartflutter", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "hubris", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "peace", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "hallucinations", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "sunlight_allergy", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "sensitivity", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "lovers_effect", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "vertigo", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "sadness", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "thin_blood", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "hatred", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "blood_poison", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "undeaf", "hawthorn")
g_pHerbCures_head = add_key(g_pHerbCures_head, "lethargy", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "berserking", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "hypersomnia", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "unblind", "bayberry")
g_pHerbCures_head = add_key(g_pHerbCures_head, "asthma", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "masochism", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "haemophilia", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "agoraphobia", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "dementia", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "paranoia", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "sandrot", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "justice", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "slickness", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "slow_salve", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "stupidity", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "nopear", "pear")
g_pHerbCures_head = add_key(g_pHerbCures_head, "hypochondria", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "epilepsy", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "loneliness", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "heartpunch", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "pacifism", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "shyness", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "addiction", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "mind_paralysis", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "dissonance", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "self-pity", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "clumsiness", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "magic_impaired", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "dizziness", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "generosity", "bellwort")
g_pHerbCures_head = add_key(g_pHerbCures_head, "weariness", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "limp_veins", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "blood_curse", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "confusion", "ash")
g_pHerbCures_head = add_key(g_pHerbCures_head, "paralysis", "bloodroot")
g_pHerbCures_head = add_key(g_pHerbCures_head, "baldness", "kelp")
g_pHerbCures_head = add_key(g_pHerbCures_head, "vomiting", "ginseng")
g_pHerbCures_head = add_key(g_pHerbCures_head, "impatience", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "commitment_fear", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "recklessness", "lobelia")
g_pHerbCures_head = add_key(g_pHerbCures_head, "infested", "goldenseal")
g_pHerbCures_head = add_key(g_pHerbCures_head, "resonance", "goldenseal")

-- :::: Rage cures

g_pRageAffs_head = add_item(g_pRageAffs_head, "hubris")
g_pRageAffs_head = add_item(g_pRageAffs_head, "pacifism")
g_pRageAffs_head = add_item(g_pRageAffs_head, "peace")
g_pRageAffs_head = add_item(g_pRageAffs_head, "justice")
g_pRageAffs_head = add_item(g_pRageAffs_head, "generosity")
g_pRageAffs_head = add_item(g_pRageAffs_head, "lovers_effect")

-- :: In-game cure order lists, the pointers of which need to be added to g_pCureListTable_head

aff_list = new_string_list()
add_item(aff_list, "cocooned")
g_pCureListTable_head = add_data(g_pCureListTable_head, "break cocoon", aff_list)

aff_list = new_string_list()
add_item(aff_list, "noaura");
g_pCureListTable_head = add_data(g_pCureListTable_head, "pipe skullcap", aff_list)

aff_list = new_string_list()
add_item(aff_list, "aeon");
add_item(aff_list, "withering");
add_item(aff_list, "hellsight");
add_item(aff_list, "deadening");
g_pCureListTable_head = add_data(g_pCureListTable_head, "pipe elm", aff_list)

aff_list = new_string_list()
add_item(aff_list, "slickness");
add_item(aff_list, "disfigurement");
g_pCureListTable_head = add_data(g_pCureListTable_head, "pipe valerian", aff_list)

-- :::: Restoration -> Head afflictions
aff_list = new_string_list()
add_item(aff_list, "head_mangled")
add_item(aff_list, "head_damaged")
add_item(aff_list, "damaged_throat")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration head", aff_list)

aff_list = new_string_list()
add_item(aff_list, "crushed_chest")
add_item(aff_list, "torso_mangled")
add_item(aff_list, "torso_damaged")
add_item(aff_list, "spinal_rip")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration torso", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "right_leg_damaged")
add_item(aff_list, "right_leg_mangled")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration right leg", aff_list)

aff_list = new_string_list()
add_item(aff_list, "left_leg_damaged")
add_item(aff_list, "left_leg_mangled")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration left leg", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "right_arm_damaged")
add_item(aff_list, "right_arm_mangled")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration right arm", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "left_arm_damaged")
add_item(aff_list, "left_arm_mangled")
g_pCureListTable_head = add_data(g_pCureListTable_head, "restoration left arm", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "anorexia")
add_item(aff_list, "gorge")
add_item(aff_list, "effused_yellowbile")
add_item(aff_list, "effused_phlegm")
add_item(aff_list, "effused_blood")
add_item(aff_list, "unknown_bile")
g_pCureListTable_head = add_data(g_pCureListTable_head, "epidermal torso", aff_list)

aff_list = new_string_list()
add_item(aff_list, "anorexia")
add_item(aff_list, "indifference")
add_item(aff_list, "stuttering")
add_item(aff_list, "blurry_vision")

add_item(aff_list, "burnt_eyes")
g_pCureListTable_head = add_data(g_pCureListTable_head, "epidermal head", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "scar")
add_item(aff_list, "crippled_throat")
add_item(aff_list, "head_bruised_critical")
add_item(aff_list, "head_bruised_moderate")
add_item(aff_list, "head_bruised")
add_item(aff_list, "throat_slash")
add_item(aff_list, "destroyed_throat")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending head", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "cracked_ribs")
add_item(aff_list, "torso_bruised_critical")
add_item(aff_list, "torso_bruised_moderate")
add_item(aff_list, "torso_bruised")
add_item(aff_list, "ablaze")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending body", aff_list)

aff_list = new_string_list()
add_item(aff_list, "leg_broken")
add_item(aff_list, "right_leg_bruised_critical")
add_item(aff_list, "right_leg_broken")
add_item(aff_list, "right_leg_bruised_moderate")
add_item(aff_list, "right_leg_bruised")
add_item(aff_list, "right_leg_dislocated")
add_item(aff_list, "left_leg_bruised_critical")
add_item(aff_list, "left_leg_broken")
add_item(aff_list, "left_leg_bruised_moderate")
add_item(aff_list, "left_leg_bruised")
add_item(aff_list, "left_leg_dislocated")
add_item(aff_list, "crushed_kneecaps")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending legs", aff_list)

aff_list = new_string_list()
add_item(aff_list, "left_leg_bruised_critical")
add_item(aff_list, "left_leg_broken")
add_item(aff_list, "left_leg_bruised_moderate")
add_item(aff_list, "left_leg_bruised")
add_item(aff_list, "left_leg_dislocated")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending left leg", aff_list)

aff_list = new_string_list()
add_item(aff_list, "right_leg_bruised_critical")
add_item(aff_list, "right_leg_broken")
add_item(aff_list, "right_leg_bruised_moderate")
add_item(aff_list, "right_leg_bruised")
add_item(aff_list, "right_leg_dislocated")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending right leg", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "arm_broken")
add_item(aff_list, "right_arm_bruised_critical")
add_item(aff_list, "right_arm_broken")
add_item(aff_list, "right_arm_bruised_moderate")
add_item(aff_list, "right_arm_bruised")
add_item(aff_list, "right_arm_dislocated")
add_item(aff_list, "left_arm_bruised_critical")
add_item(aff_list, "left_arm_broken")
add_item(aff_list, "left_arm_bruised_moderate")
add_item(aff_list, "left_arm_bruised")
add_item(aff_list, "left_arm_dislocated")
add_item(aff_list, "crushed_elbows")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending arms", aff_list)

aff_list = new_string_list()
add_item(aff_list, "left_arm_bruised_critical")
add_item(aff_list, "left_arm_broken")
add_item(aff_list, "left_arm_bruised_moderate")
add_item(aff_list, "left_arm_bruised")
add_item(aff_list, "left_arm_dislocated")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending left arm", aff_list)

aff_list = new_string_list()
add_item(aff_list, "right_arm_bruised_critical")
add_item(aff_list, "right_arm_broken")
add_item(aff_list, "right_arm_bruised_moderate")
add_item(aff_list, "right_arm_bruised")
add_item(aff_list, "right_arm_dislocated")
g_pCureListTable_head = add_data(g_pCureListTable_head, "mending right arm", aff_list)

	
aff_list = new_string_list()
add_item(aff_list, "slickness")
add_item(aff_list, "disfigurement")
g_pCureListTable_head = add_data(g_pCureListTable_head, "valerian", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "paralysis")
add_item(aff_list, "mirroring")
add_item(aff_list, "crippled_body")
add_item(aff_list, "crippled")
add_item(aff_list, "slickness")
add_item(aff_list, "sandrot")
add_item(aff_list, "heartflutter")
g_pCureListTable_head = add_data(g_pCureListTable_head, "bloodroot", aff_list)
	
aff_list = new_string_list()
add_item(aff_list, "self-pity")
add_item(aff_list, "stupidity")
add_item(aff_list, "dizziness")
add_item(aff_list, "shyness")
add_item(aff_list, "epilepsy")
add_item(aff_list, "impatience")
add_item(aff_list, "resonance")
add_item(aff_list, "dissonance")
add_item(aff_list, "infest")
g_pCureListTable_head = add_data(g_pCureListTable_head, "goldenseal", aff_list)

aff_list = new_string_list()
add_item(aff_list, "hubris")
add_item(aff_list, "pacifism")
add_item(aff_list, "peace")
add_item(aff_list, "lovers_effect")
add_item(aff_list, "superstition")
add_item(aff_list, "generosity")
add_item(aff_list, "justice")
g_pCureListTable_head = add_data(g_pCureListTable_head, "bellwort", aff_list)

aff_list = new_string_list()
add_item(aff_list, "baldness")
add_item(aff_list, "clumsiness")
add_item(aff_list, "magic_impaired")
add_item(aff_list, "hypochondria")
add_item(aff_list, "weariness")
add_item(aff_list, "asthma")
add_item(aff_list, "limp_veins")
add_item(aff_list, "sensitivity")
add_item(aff_list, "blood_poison")
g_pCureListTable_head = add_data(g_pCureListTable_head, "kelp", aff_list)

aff_list = new_string_list()
add_item(aff_list, "commitment_fear")
add_item(aff_list, "recklessness")
add_item(aff_list, "masochism")
add_item(aff_list, "agoraphobia")
add_item(aff_list, "loneliness")
add_item(aff_list, "vertigo")
add_item(aff_list, "claustrophobia")
add_item(aff_list, "berserking")
g_pCureListTable_head = add_data(g_pCureListTable_head, "lobelia", aff_list)

aff_list = new_string_list()
add_item(aff_list, "body_odor")
add_item(aff_list, "haemophilia")
add_item(aff_list, "sunlight_allergy")
add_item(aff_list, "mental_disruption")
add_item(aff_list, "physical_disruption")
add_item(aff_list, "vomiting")
add_item(aff_list, "thin_blood")
add_item(aff_list, "rend")
add_item(aff_list, "lethargy")
add_item(aff_list, "addiction")
g_pCureListTable_head = add_data(g_pCureListTable_head, "ginseng", aff_list)

aff_list = new_string_list()
add_item(aff_list, "sadness")
add_item(aff_list, "dementia")
add_item(aff_list, "hallucinations")
add_item(aff_list, "confusion")
add_item(aff_list, "paranoia")
add_item(aff_list, "hypersomnia")
add_item(aff_list, "hatred")
add_item(aff_list, "blood_curse")
add_item(aff_list, "blight")
g_pCureListTable_head = add_data(g_pCureListTable_head, "ash", aff_list)

aff_list = new_string_list()
add_item(aff_list, "undeaf")
g_pCureListTable_head = add_data(g_pCureListTable_head, "hawthorn", aff_list)

aff_list = new_string_list()
add_item(aff_list, "unblind")
g_pCureListTable_head = add_data(g_pCureListTable_head, "bayberry", aff_list)

aff_list = new_string_list()
add_item(aff_list, "insomnia")
g_pCureListTable_head = add_data(g_pCureListTable_head, "cohosh", aff_list)

aff_list = new_string_list()
add_item(aff_list, "voyria")
g_pCureListTable_head = add_data(g_pCureListTable_head, "immunity", aff_list)